version: "3.8"

services:
  postgres-db:
    image: postgres:13.1-alpine
    env_file: .env
    restart: always
    networks:
      - db-network-private
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:

networks:
  db-network-private:
    external: true
